target-version = "py310"
line-length = 88
extend-exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
]

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
]

ignore = [
    "E501",  # line too long (handled by black)
    "E203",  # whitespace before ':'
]

[lint.per-file-ignores]
"tests/*" = ["F401"]  # Allow unused imports in tests
"xfusion_lite.py" = ["F401"]  # Allow unused imports in validation function

[lint.isort]
known-first-party = ["xfusion"]
