# general settings
name: train_SwinVR_STFx4_scratch
model_type: SwinIRModel
scale: 4
num_gpu: 4
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: XRAY
    type: XrayDatasetSTF
    flag: grayscale
    dataroot_gt: ~
    dataroot_lq: ~
    dataroot_flow: ~
    meta_info_file: ~
    val_partition: official
    io_backend:
      type: disk

    num_frame: 3
    num_frame_hi: 2
    gt_size: 96
    interval_list: [1,2,3]
    hi_interval_mult: 20
    random_reverse: false
    use_hflip: true
    use_rot: true
    use_local_renorm: false
    poisson_noise_b0_exp: [1,7]

    # data loader
    num_worker_per_gpu: 3
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: XRAY
    type: XrayVideoTestDatasetSTF
    flag: grayscale
    dataroot_gt: ~
    dataroot_lq: ~
    meta_info_file: ~
    io_backend:
      type: disk

    cache_data: false
    num_frame: 3
    num_frame_hi: 2
    padding: reflection_circle
    use_local_renorm: false

# network structures
network_g:
  type: PatchTransformerSTF
  upscale: 4
  num_in_ch: 1
  num_frame: 3
  window_size: [5,8,8]
  depths: [2,2,18,2]
  embed_dim: 192
  num_heads: [3,3,3,3]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
